# rds.tf — RDS PostgreSQL major 16 datastore (§12, §4 Flyway owns schema).
#
# SAFETY (rule #7 / RISK-016): the master password is generated by random_password
# and passed to RDS; it lives ONLY in (encrypted, access-controlled S3) Terraform
# state and is NEVER an output or a log line. The 12.6 `db` Secrets Manager secret
# (NOT this slice) consumes aws_db_instance.wc.address/port + random_password.db.result
# to populate spring.datasource.* (Appendix D.2). This slice exposes only
# `rds_endpoint` (host:port — no credentials).

# Master password (Pattern 2 — matches the Appendix D.2 single-`db`-secret contract).
# RDS disallows '/', '@', '"', and space in the master password — override_special
# excludes them (and URL/shell troublemakers) so the value is safe wherever the
# db secret is later consumed.
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%*()-_=+"
}

resource "aws_db_subnet_group" "wc" {
  name       = "${local.cluster_name}-db"
  subnet_ids = module.vpc.private_subnets # private subnets only, ≥2 AZ (subnet-group requirement)
  tags       = local.common_tags
}

# Dedicated RDS security group — ingress 5432 from the EKS node group ONLY.
resource "aws_security_group" "rds" {
  name        = "${local.cluster_name}-rds"
  description = "RDS PostgreSQL - ingress 5432 from EKS node group only"
  vpc_id      = module.vpc.vpc_id
  tags        = local.common_tags
}

# SG-to-SG ingress: source is the node SG (LESSONS §6: node_security_group_id is
# the eks-v21 node SG). No cidr_ipv4 / 0.0.0.0/0 — the DB is reachable only from
# the cluster's nodes. SGs are stateful, so no egress rule is required.
resource "aws_vpc_security_group_ingress_rule" "rds_from_nodes" {
  security_group_id            = aws_security_group.rds.id
  referenced_security_group_id = module.eks.node_security_group_id
  from_port                    = 5432
  to_port                      = 5432
  ip_protocol                  = "tcp"
  description                  = "PostgreSQL 5432 from EKS node group only"
}

resource "aws_db_instance" "wc" {
  identifier = "${local.cluster_name}-db"

  engine                     = "postgres"
  engine_version             = var.rds_minor_version # 16.x (RISK-011; 12.1 ^16. validation)
  auto_minor_version_upgrade = true

  instance_class    = var.rds_instance_class
  allocated_storage = var.rds_allocated_storage
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = "wc"
  username = "wc_app"
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.wc.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false # HARDCODED — not a variable, cannot be flipped on
  multi_az               = var.rds_multi_az

  backup_retention_period = var.rds_backup_retention_period

  # MVP/demo posture (thin, like single-NAT/single-AZ) — clean `terraform destroy`.
  # Hardening (deletion_protection=true + final snapshot) is a Phase 13 trims item.
  skip_final_snapshot = true
  deletion_protection = false

  tags = local.common_tags
}
